- hosts: all
  vars:
    bindep_profile: test
  tasks:
    - name: Install requirements
      pip:
        chdir: "{{ zuul_work_dir }}"
        virtualenv: "{{ zuul_work_virtualenv }}"
        requirements: requirements.txt

    - name: Install the project from source
      pip:
        chdir: "{{ zuul_work_dir }}"
        virtualenv: "{{ zuul_work_virtualenv }}"
        name: .

    - name: Run bindep with the file
      command: >
        {{ zuul_work_virtualenv }}/bin/bindep -b -f
        "{{ ansible_user_dir }}/{{ zuul.projects['git.openstack.org/openstack-infra/bindep'].src_dir }}/bindep/tests/bindep.txt"
        {{ bindep_profile }}
      register: _bindep_output
      changed_when: false
      failed_when: false

    - name: Install distro packages from bindep
      package:
        name: "{{ _bindep_output.stdout_lines }}"
        state: present
      become: yes
      when: _bindep_output.stdout_lines
